os:
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

# branches:
#   except:
#     - gh-pages
#     - benchmarks

environment:
  fast_finish: true
  global:
    DRMEMORY: "drmemory -light -batch -exit_code_if_errors 1"

  matrix:
  - CFG: cmake

matrix:
  fast_finish: true

install:
  - cinst drmemory
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - git submodule update --init --recursive
  - set PATH=C:\Program Files (x86)\Dr. Memory\bin;%PATH%

build_script:
  - IF %CFG%==cmake pushd . && cd build && cmake .. && cmake --build .
