language: c++
sudo: required
matrix:
  fast_finish: true
  include:
    - os: osx
      env: TOOLSET=clang COMPILER=clang++

    - os: linux



  # - os: osx
  #   env: CMAKE=ON COMPILER=clang++
  # - os: osx
  #   osx_image: xcode7
  #   env: TOOLSET=clang COMPILER=clang++
  # - os: osx
  #   osx_image: xcode7
  #   env: CMAKE=ON BENCHMARK=ON COMPILER=clang++

before_script:
- git config --global user.name "Travis-CI"
- git config --global user.email "travis@ci.net"
- git config --global push.default simple
- (cd build && ./bootstrap.sh)

before_install:
#  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew install boost); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then (sudo apt-get install -qq libboost-test-dev); fi


install:
- export CXX="${COMPILER}"
- if [ "${LIBCXX}" != "" ]; then (svn --quiet co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
  && cd libcxx/lib && ./buildit && ln -f -s libc++.so.1.0 libc++.so.1)
  && export CXXFLAGS="-stdlib=libc++ -I${TRAVIS_BUILD_DIR}/libcxx/include"
  && export LDFLAGS="-L${TRAVIS_BUILD_DIR}/libcxx/lib -lc++"
  && export LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/libcxx/lib:$LD_LIBRARY_PATH"; fi

script:
-        make
-        ./race

