language: c++
sudo: required
matrix:
  fast_finish: true
  include:
    - os: osx

    - os: osx
      env: COMPILER=clang++
      osx_image: xcode7

    - os: osx
      env: COMPILER=clang++ TOOLCHAIN=analyze
      osx_image: xcode7

    # unsupported
    # - os: osx
    #   env: COMPILER=clang++ TSAN=1
    #   osx_image: xcode7

    - os: osx
      env: COMPILER=clang++ ASAN=1
      osx_image: xcode7

    - os: linux
      env: COMPILER=g++-4.8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.8
          - g++-4.8

    - os: linux
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5

    - os: linux
      env: COMPILER=g++-5 VALGRIND_ENABLED=1
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - valgrind

    - os: linux
      env: COMPILER=g++-5 ASAN=1
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5

    - os: linux
      env: COMPILER=g++-5 TSAN=1
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.7 CLANG_TIDY=1
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
          packages:
          - clang-3.7
          - libstdc++-5-dev

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.7
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
          packages:
          - clang-3.7
          - libstdc++-5-dev

before_script:
- git config --global user.name "Travis-CI"
- git config --global user.email "travis@ci.net"
- git config --global push.default simple

install:
- if [ "$COMPILER" != "" ]; then export CXX=$COMPILER ; fi
    
script:
- $CXX --version
- make && ./.travis.sh


